# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7s15ftgb196-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/summerclass/bighomework/bighomework.cache/wt [current_project]
set_property parent.project_path F:/summerclass/bighomework/bighomework.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  f:/summerclass/clk_division/clk_division.srcs/sources_1/new/ip_user_files
  f:/summerclass/clk_division/clk_division.srcs/sources_1/new
} [current_project]
update_ip_catalog
set_property ip_output_repo f:/summerclass/bighomework/bighomework.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files F:/summerclass/bighomework/bighomework.srcs/sources_1/imports/bighomework/filter.coe
read_verilog -library xil_defaultlib F:/summerclass/bighomework/bighomework.srcs/sources_1/new/main.v
read_ip -quiet F:/summerclass/bighomework/bighomework.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0.xci
set_property used_in_implementation false [get_files -all f:/summerclass/bighomework/bighomework.srcs/sources_1/ip/fir_compiler_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all f:/summerclass/bighomework/bighomework.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0_ooc.xdc]

read_ip -quiet f:/summerclass/bighomework/bighomework.srcs/sources_1/ip/clk_division_0/clk_division_0.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/summerclass/bighomework/bighomework.srcs/constrs_1/new/system.xdc
set_property used_in_implementation false [get_files F:/summerclass/bighomework/bighomework.srcs/constrs_1/new/system.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top main -part xc7s15ftgb196-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef main.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
